package org.integrallis.drools.genealogy;
 
import org.integrallis.drools.genealogy.SiblingRelationship.SiblingType;
import java.util.List;

rule "HalfSiblings"
	when
        person1: Person()
        person2: Person()
	then 	
		insert(new SiblingRelationship(person1, person2, SiblingType.HALF_SIBLING));
end

rule "Siblings"
	when
		person1: Person()
        person2: Person()
	then 	
		insert(new SiblingRelationship(person1, person2, SiblingType.SIBLING));
end

rule "PrintRelationships"
    when
        relationship: SiblingRelationship()
    then
        relationship.printIt();
end

query "getAllRelationships"
    relationship: SiblingRelationship()
end
