package org.integrallis.drools.genealogy;
 
import org.integrallis.drools.genealogy.SiblingRelationship.SiblingType;
import java.util.List;

rule "HalfSiblings"
	when
		person1: Person(
		    p1mother: mother != null, 
		    p1father: father != null
		)
		person2: Person(
		    mother != null, 
		    father != null, 
		    (
		     ((parents contains p1mother) && (parents not contains p1father)) || 
		     ((parents not contains p1mother) && (parents contains p1father))
		    ),
		    this != person1
		) 
		not SiblingRelationship(members contains person1, members contains person2)
	then 	
		insert(new SiblingRelationship(person1, person2, SiblingType.HALF_SIBLING));
end

rule "Siblings"
	when
		person1: Person(
		    p1mother: mother != null, 
		    p1father: father != null
		)
		person2: Person(
		    mother != null, 
		    father != null, 
		    mother == p1mother, 
		    father == p1father, 
		    this != person1
		) 
		not SiblingRelationship(members contains person1, members contains person2)
	then 	
		insert(new SiblingRelationship(person1, person2, SiblingType.SIBLING));
end

rule "PrintRelationships"
    when
        relationship: SiblingRelationship()
    then
        relationship.printIt();
end

query "getAllRelationships"
    relationship: SiblingRelationship()
end
